#!/usr/bin/env php
<?php

require __DIR__.'/vendor/autoload.php';

$app = require_once __DIR__.'/bootstrap/app.php';

$app->handle(
    request: Illuminate\Http\Request::capture(),
    response: new Symfony\Component\Console\Output\ConsoleOutput()
);
